services:
  postgres:
    image: postgres:latest
    env_file:
      - ../../servers/.env
    ports:
      - "5432:5432"
    networks:
      - hackcation-dev-network
    volumes:
      - hackcation-dev-postgres-volume:/var/lib/postgresql/data

  voter-http:
    build:
      context: ../../
      dockerfile: docker/dev/servers/voter-http/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../../servers/.env
    depends_on:
      - postgres
    networks:
      - hackcation-dev-network
    volumes:
      - ../../servers/cmd:/app/cmd
      - ../../servers/internal:/app/internal
      - ../../servers/go.mod:/app/go.mod
      - ../../servers/go.sum:/app/go.sum

networks:
  hackcation-dev-network:
    driver: bridge

volumes:
  hackcation-dev-postgres-volume: { }

