services:
  postgres:
    image: postgres:latest
    env_file:
      - ../../servers/.env
    ports:
      - "5432:5432"
    networks:
      - hackcation-prod-network
    volumes:
      - hackcation-prod-postgres-volume:/var/lib/postgresql/data
    restart: unless-stopped

  voter-server:
    build:
      context: ../../
      dockerfile: docker/prod/servers/voter/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../../servers/.env
    depends_on:
      - postgres
    networks:
      - hackcation-prod-network
    restart: unless-stopped

  home-site:
    build:
      context: ../../
      dockerfile: docker/prod/clients/home/Dockerfile
    networks:
      - hackcation-prod-network
    restart: unless-stopped

  voter-app:
    build:
      context: ../../
      dockerfile: docker/prod/clients/voter/Dockerfile
    networks:
      - hackcation-prod-network
    restart: unless-stopped

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - hackcation-prod-caddy-data:/data
      - hackcation-prod-caddy-config:/config
    networks:
      - hackcation-prod-network
    depends_on:
      - voter-server
      - home-site
      - voter-app

networks:
  hackcation-prod-network:
    driver: bridge

volumes:
  hackcation-prod-postgres-volume: { }
  hackcation-prod-caddy-data: {}
  hackcation-prod-caddy-config: {}

